# Generated by Django 4.2.26 on 2025-11-11 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=10)),
                ('house', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type_name', models.CharField(max_length=100)),
                ('defect_percentage', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsite.cities')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('article', models.CharField(max_length=50)),
                ('min_partner_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polsite.materialtype')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsite.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(choices=[('ЗАО', 'ЗАО'), ('ООО', 'ООО'), ('ПАО', 'ПАО'), ('ОАО', 'ОАО')], max_length=10)),
                ('partner_name', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('inn', models.CharField(max_length=12)),
                ('rating', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsite.address')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sale_date', models.DateTimeField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsite.partners')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsite.products')),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsite.regions'),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polsite.streets'),
        ),
    ]
